services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-stats
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/stats-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/ewm-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=54321
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-server:
    build:
      context: ./stats-service/stats-service-server
      dockerfile: Dockerfile
    image: stats-server
    container_name: stats-server
    ports:
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-gateway:
    build:
      context: ./stats-service/stats-service-gateway
      dockerfile: Dockerfile
    image: stats-gateway
    container_name: stats-gateway
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9091

  ewm-service:
    build:
      context: ./main-service/main-service-server
      dockerfile: Dockerfile
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8081:8081"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=54321

  ewm-gateway:
    build:
      context: ./main-service/main-service-gateway
      dockerfile: Dockerfile
    image: ewm-gateway
    container_name: ewm-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service
    environment:
      - MAIN_SERVER_URL=http://ewm-service:8081/